name: .NET Tool CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: CopyFlatten.slnx
      Configuration: Release

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x

    - name: Restore dependencies
      run: dotnet restore $env:Solution_Name

    - name: Build
      run: dotnet build $env:Solution_Name --configuration $env:Configuration --no-restore

    - name: Pack
      run: dotnet pack CopyFlatten/CopyFlatten.csproj --configuration $env:Configuration --no-build --output ./artifacts

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CopyFlatten-NuGet
        path: ./artifacts/*.nupkg
